version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: devfolio-postgres
    environment:
      POSTGRES_DB: devfolio
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: devfolio-backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
      - ./backend/create_user.py:/app/create_user.py
      - ./backend/requirements.txt:/app/requirements.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    container_name: devfolio-frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    container_name: devfolio-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./admin-dashboard/dist:/usr/share/nginx/html/admin:ro

volumes:
  postgres-data:
