FROM python:3.11-slim

WORKDIR /app
COPY ./app ./app
COPY ./uploads ./uploads
COPY create_user.py /app/create_user.py
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
